### PR TITLE
Fix issue#70

### PR DESCRIPTION
**Pull request by mjyc**
A quick fix based on findings from https://github.com/dspinellis/git-issue/issues/70#issuecomment-606142066

### CODE REVIEW

**Comment by dspinellis** [comment]
Is this covered by PR #73? Why are we changing the `Link` header match?

**Comment by mjyc** [comment]
Opps, I used a wrong comment reference, the correct one is at here https://github.com/dspinellis/git-issue/issues/70#issuecomment-607022134

I temporarily introduce `Link` header match because I didn't know about what existing `'^\(Status: 200\|HTTP/[[:digit:]].[[:digit:]] 200 OK\)'` match was doing, which I now think is a better rule to use.

**Comment by mjyc** [comment]
Also is not covered by #73; that PR is fixing an export related problem and this one is fixing an import related problem (but essentially the same cause)

**Comment by dspinellis** [comment]
Thank you for the explanation!  To avoid a confusing history, can you please force push a patch without the intermediate Link header match?

**Comment by mjyc** [comment]
Modified commit history as requested

**Comment by dspinellis** [comment]
Thank you!

**Pull request merged**
